---
- name: Configure proxy
  hosts: localhost
  gather_facts: no
  vars:
    proxy_url: 
    proxy_port:
    proxy_name:
    proxy_listen_port:
    proxy_upstream:
    proxy_upstream_port:
    disable_proxy: false
    toxic_name: response_latency
    toxic_type: latency

  tasks:
    - name: Ensure proxy exists
      cloin.toxiproxy.proxy:
        url: "{{ proxy_url }}"
        name: "{{ proxy_name }}"
        listen: "[::]:{{ proxy_listen_port }}"
        upstream: "{{ proxy_upstream }}:{{ proxy_upstream_port }}"
        state: "present"

    - name: Create a latency toxic
      cloin.toxiproxy.toxic:
        url: "{{ proxy_url }}"
        proxy_name: "{{ proxy_name }}"
        toxic_name: "{{ toxic_name }}"
        toxic_type: "{{ toxic_type }}"
        attributes:
          latency: 5000
          jitter: 500
        state: "present"

    - name: Delete latency toxic
      when: disable_toxic
      cloin.toxiproxy.toxic:
        url: "{{ proxy_url }}"
        proxy_name: "{{ proxy_name }}"
        toxic_name: "{{ toxic_name }}"
        toxic_type: "{{ toxic_type }}"
        attributes:
          latency: 5000
          jitter: 500
        state: "absent"