- name: Rulebook to do something
  hosts: localhost
  gather_facts: false

  sources:
    - ansible.eda.file:
      files:
        - /tmp/demo.txt

  rules:
      - name: trigger on range
        condition: event.change == 'created' # 'modified'
        action:
          run_job_template:
            name: "Remediate file perms"
            organization: Default
            post_events: true

# https://jpmens.net/2023/08/14/using-events-to-drive-ansible/