- name: Rulebook for remediating file perms
  hosts: all
  gather_facts: false
  sources:
    - name: file
      ansible.eda.file:
      files:
        - "demo.yml"
  rules:
    - name: Debug event
      condition: event.meta is defined
      action:
        debug:

