- name: SNOW events
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Catch all ServiceNow events
      condition: event.meta.endpoint == "servicenow"
      action:
        debug: