- name: SNOW events
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Debug event
      condition: event.meta is defined
      action:
        debug: