---
- name: Configure proxy
  hosts: localhost
  gather_facts: no
  vars:
    proxy_url: 
    proxy_port:
    proxy_name:
    proxy_listen_port:
    proxy_upstream:
    proxy_upstream_port:

  tasks:
    - name: Create a Toxiproxy proxy
      cloin.toxiproxy.proxy:
        url: "{{ proxy_url }}"
        name: "{{ proxy_name }}"
        listen: "[::]:{{ proxy_listen_port }}"
        upstream: "{{ proxy_upstream }}:{{ proxy_upstream_port }}"
        state: "present"
